language: php
sudo: yes
php:
    - 7.1
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer update --no-interaction --prefer-source
script:
  # set PATH
  - export PATH=/usr/bin:/bin:/snap/bin:$PATH
  # install 
  - sudo apt-get update
  - sudo apt-get -y install wget
  # setup LXD group
  - sudo groupadd --system lxd
  - sudo usermod -a -G lxd $USER
  - wget https://gist.githubusercontent.com/lcherone/d7e5ba660bc20d738132ccb1a453459d/raw/ba46a36952a3c7461cd1219c8a1a2fdd35a18e91/install.sh && sudo bash install.sh -s
  
  # exit on fail
  #- set -eo pipefail
  # install lxd
  #- sudo apt-get --yes install snapd
  #- sudo snap install lxd
  #- sudo lxd waitready
  #- sudo lxd init --auto --network-address="127.0.0.1" --storage-backend=dir --trust-password=$lxdSecret
  # setup LXD REST api
  #- openssl genrsa 2048 > client.key
  #- openssl req -new -x509 -nodes -sha1 -days 365 -key client.key -out client.crt -subj "/C=GB/ST=London/L=London/O=TEST/OU=IT Department/CN=ssl.cherone.co.uk"
  #- sudo lxd.lxc config trust add client.crt
  #- curl -k -L --cert client.crt --key client.key "https://127.0.0.1:8443/1.0"
  #- composer test